version = 1

[[battery-pack]]
name = "cli"
features = ["default"]

[[battery-pack.managed-deps]]
name = "clap"
version = "4"

[[battery-pack.managed-deps]]
name = "snapbox"
version = "1.2.1"

[[battery-pack]]
name = "ci"
features = ["default"]
managed-deps = []
applied-templates = ["full"]
